// <auto-generated />
using System;
using LibraryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApp.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20250605111143_test_v3")]
    partial class test_v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryApp.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            FirstName = "Admin1Name",
                            LastName = "Admin1LastName"
                        },
                        new
                        {
                            AdminId = 2,
                            FirstName = "Admin2Name",
                            LastName = "Admin2LastName"
                        },
                        new
                        {
                            AdminId = 3,
                            FirstName = "Admin3Name",
                            LastName = "Admin3LastName"
                        },
                        new
                        {
                            AdminId = 4,
                            FirstName = "Admin4Name",
                            LastName = "Admin4LastName"
                        },
                        new
                        {
                            AdminId = 5,
                            FirstName = "Admin5Name",
                            LastName = "Admin5LastName"
                        });
                });

            modelBuilder.Entity("LibraryApp.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            LastName = "Author1LastName",
                            Name = "Author1Name"
                        },
                        new
                        {
                            AuthorId = 2,
                            LastName = "Author2LastName",
                            Name = "Author2Name"
                        },
                        new
                        {
                            AuthorId = 3,
                            LastName = "Author3LastName",
                            Name = "Author3Name"
                        },
                        new
                        {
                            AuthorId = 4,
                            LastName = "Author4LastName",
                            Name = "Author4Name"
                        });
                });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Isbn");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Isbn = "123456oaihsf",
                            Available = true,
                            Genre = "Avantura",
                            Title = "Alisa u zemlji cuda"
                        },
                        new
                        {
                            Isbn = "asdffrghsf",
                            Available = true,
                            Genre = "Avantura",
                            Title = "Lord of rings"
                        },
                        new
                        {
                            Isbn = "127889asdihsf",
                            Available = true,
                            Genre = "Avantura",
                            Title = "Harry Potter"
                        },
                        new
                        {
                            Isbn = "deilgoihj2343",
                            Available = true,
                            Genre = "Avantura",
                            Title = "Murder on Nil"
                        },
                        new
                        {
                            Isbn = "123456oadadadasf",
                            Available = true,
                            Genre = "Avantura",
                            Title = "Le Petite Prince"
                        },
                        new
                        {
                            Isbn = "189er56oaihsf",
                            Available = true,
                            Genre = "Avantura",
                            Title = "The jungle book"
                        });
                });

            modelBuilder.Entity("LibraryApp.Models.Customer", b =>
                {
                    b.Property<int>("JMBG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JMBG"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JMBG");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            JMBG = 123456,
                            FirstName = "Customer1Name",
                            LastName = "Customer1LastName"
                        },
                        new
                        {
                            JMBG = 239184762,
                            FirstName = "Customer2Name",
                            LastName = "Customer2LastName"
                        },
                        new
                        {
                            JMBG = 329456,
                            FirstName = "Customer3Name",
                            LastName = "Customer3LastName"
                        },
                        new
                        {
                            JMBG = 324857,
                            FirstName = "Customer4Name",
                            LastName = "Customer4LastName"
                        },
                        new
                        {
                            JMBG = 238476,
                            FirstName = "Customer5Name",
                            LastName = "Customer5LastName"
                        });
                });

            modelBuilder.Entity("LibraryApp.Models.Rent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("Rents");
                });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.HasOne("LibraryApp.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibraryApp.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
